# source .zshrc
alias sz='source ~/.zshrc'

# krew
export PATH="${KREW_ROOT:-$HOME/.krew}/bin:$PATH"

# Syntax highlighting for better readability in the terminal
source /opt/homebrew/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

# Enable colors in the terminal
export CLICOLOR=1

# Set terminal type to support 256 colors
export TERM=xterm-256color

# Initialize starship for a custom prompt with additional features
eval "$(starship init zsh)"

# Source the kube-ps1 script to enable Kubernetes context in the prompt
source "/opt/homebrew/opt/kube-ps1/share/kube-ps1.sh"
PS1='$(kube_ps1)'$PS1

# Initialize completion system
autoload -Uz compinit
compinit

# Kubernetes kubectl autocompletion
compdef _kubectl kubectl

# Set PATH for OpenSSL installed via Homebrew
export PATH=$(brew --prefix openssl)/bin:$PATH


# Set GOROOT for Go language
export GOROOT="$(brew --prefix golang)/libexec"

# Additional PATH for user-installed Go binaries
export PATH=$PATH:/Users/taniwa/go/bin/

# Aliases for common Kubernetes commands
alias k='kubectl'
alias ktx='kubectx'
alias kns='kubens'
alias kk='kubectl krew'

# Alias for Docker command
alias d='docker'

alias fzfv='vim $(fzf)'
alias fzfg='git checkout $(git branch | fzf)'
alias fzfk='kill -9 $(ps aux | fzf | awk '{print $2}')'
alias fzfd='cd $(find * -type d | fzf)'
alias fzff='find . -type f | fzf'

# FZF configuration for better search experience
export FZF_DEFAULT_OPTS='--height 60% --reverse --border --exact'

# Alias to change directory to a selected repository using ghq and fzf
alias g='cd $(ghq list -p | fzf --preview "cat {}/README.md")'

# Alias to checkout a GitHub pull request using gh and fzf
alias gco='gh pr checkout $(gh pr list | fzf | awk '\''{ print $1 }'\'')'

# Alias to commit with sign-off in git
alias gcs='git commit -s'

# Rancher Desktop path configuration (auto-generated by Rancher Desktop)
### MANAGED BY RANCHER DESKTOP START (DO NOT EDIT)
export PATH="/Users/taniwa/.rd/bin:$PATH"
### MANAGED BY RANCHER DESKTOP END (DO NOT EDIT)
